/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;

import java.io.FileNotFoundException;

import static org.junit.Assert.*;

public class AppTest {

    @Test(expected = FileNotFoundException.class)
    public void testPathToSeeIfExists () throws FileNotFoundException {
        GetQuotes.randomQuote("asdasdasd");
    }
}


