/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Random;
import java.util.Scanner;

public class App {

    public static void main(String[] args) throws FileNotFoundException {
       GetQuotes test = new GetQuotes();
       test.randomQuote(  "src/main/resources/recentquotes.json ");

    }


}

class GetQuotes {

    public static void randomQuote(String pathname) throws FileNotFoundException {
    Gson gson = new Gson();

    String path = pathname;

    File recentQuotesFile = new File(pathname);
    String inputString = "";

        try {
        Scanner scanner = new Scanner(new File(path));

        while (scanner.hasNext()) {
            inputString += scanner.nextLine();
        }
        scanner.close();


    } catch (FileNotFoundException e) {
        throw e;
    }


    RecentQuotes[] quoteArray = gson.fromJson(inputString, RecentQuotes[].class);
        Random randomQuotes = new Random();
        int n = (int) Math.ceil(Math.random() * quoteArray.length) ;
        System.out.println(quoteArray[n]);
    }


}
