/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
import com.google.gson.Gson;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Random;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        Gson gson = new Gson();

        String path = "src/main/resources/recentquotes.json ";

        File recentQuotesFile = new File("src/main/resources/recentquotes.json");
        String inputString= "";

        try {
            Scanner scanner = new Scanner(new File(path));

            while (scanner.hasNext()){
                inputString+=scanner.nextLine();
            }
            scanner.close();


        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

        Random randomQuotes = new Random();



        RecentQuotes[] quoteArray= gson.fromJson(inputString, RecentQuotes[].class);
        System.out.println("quoteArray[10]= " + quoteArray[10]);

        
        

    }




}