/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URL;
import java.util.Random;
import java.util.Scanner;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;

public class App {

    public static void main(String[] args) throws FileNotFoundException {
//       GetQuotes test = new GetQuotes();
//       test.randomQuote(  "src/main/resources/recentquotes.json ");

        try {
            System.out.println(GetQuotes.randomJokes());
        } catch (IOException e) {
            e.printStackTrace();
        }

    }



}

